language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python bottle-test.py
# - pytest
